DROP INDEX IF EXISTS idx_name;
DROP INDEX IF EXISTS idx_sku;
DROP INDEX IF EXISTS idx_category;
DROP INDEX IF EXISTS idx_price;
DROP INDEX IF EXISTS idx_created_at;
DROP INDEX IF EXISTS idx_deleted_at;

DROP TABLE IF EXISTS products
