name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          docker build -t my-go-app:latest .
          
          docker tag my-go-app:latest $ECR_REGISTRY:latest

          docker push $ECR_REGISTRY:latest

      - name: Log out of Docker
        run: docker logout ${{ secrets.ECR_REPOSITORY }}